Handle missing coach
Add an explicit check if a team is missing a coach when generating the
school information file. Log an error and continue with the next
school. Eliminates the following error:
AttributeError: 'NoneType' object has no attribute 'FirstName'